### PR TITLE
don't error if `unicore.hub` credentials aren't provided

### PR DESCRIPTION
**Pull request by Rizziepit**

### CODE REVIEW

**Comment by Rizziepit** [comment]
@miltontony if the hubclient isn't configured and someone hits one of the auth views, they'll just be redirected back to their original page now

**Comment by miltontony** [comment]
Could you add a test for this please? It's probably trivial

**Comment by Rizziepit** [comment]
sure

**Comment by Rizziepit** [comment]
@miltontony a wild test appears!

**Comment by miltontony** [comment]
:+1: :joy:

**Pull request merged**
